name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    concurrency:
      group: ${{ github.repository }}-${{ github.head_ref }}
      cancel-in-progress: true
    uses: bobrossthepainter/github-workflows/.github/workflows/ghcr-build.yaml@main
    with:
      multi-arch: linux/amd64,linux/arm64
